Feature: CSSPPFIP-25_alternative_2 going back after widow focus change

As I user I want see the table elements with current data after the app goes back to the foreground

Background:
	Given I run the app
	And I have Internet connection
	And there's connection to the server
	And the game is on

Scenario outline: Window focus change
	
	When there is a <"window_focus_change">
	And I put the app back to the foreground after "given amount of time"
	And there are statistics available on the server

	| player_name  | scoreLabel | killsLabel | deathsLabel | assistsLabel | mvpLabel |
	| Pasha        | ...
	| Guru         | ...
	| BOT_Yani     | ...
	| Goat         | ...
	| BOT_Fred     | ...
	| SerekWiejski | ...
	| Nani         | ...
	| Lollipop     | ...
	| Fluffy       | ...
	| Amsterdam    | ...

	Then the folliwng label_text should be displayed:

	| label_text  |
	| player_name |
	| assistsLabel| 
	| deathsLabel |
	| mvpLabel    |
	| scoreLabel  |
	
	And I should see the current data:

	| player_name  | scoreLabel | killsLabel | deathsLabel | assistsLabel | mvpLabel |
	| Pasha        | ...
	| Guru         | ...
	| BOT_Yani     | ...
	| Goat         | ...
	| BOT_Fred     | ...
	| SerekWiejski | ...
	| Nani         | ...
	| Lollipop     | ...
	| Fluffy       | ...
	| Amsterdam    | ...

	Examples:
	| window_focus_change                                  |
	| incoming call                                        |
	| putting app in the background                        |
	| app in the background while using another another app|
