platform :ios, '10.0'

# Pods used by CSGOSpectatorKit
def spectatorKit_pods
    pod 'Alamofire', '~> 4.7'
end

# Pods used by both targets
def shared_pods
    pod 'SwiftLint'
end

target 'CSGOSpectator' do

    use_frameworks!
    
    shared_pods

  # Pods for CSGOSpectator

  target 'CSGOSpectatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CSGOSpectatorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


target 'CSGOSpectatorKit' do
    
    use_frameworks!
    
  spectatorKit_pods
  shared_pods

  target 'CSGOSpectatorKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
